# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b80fef1112387978b1a3898d963e65cb1a320c05c9d5438654fc3942eb408ea6aed8b025482a0cfe1507c2f474caeaf1b638d62dd91e93829e0febfe09424e5

test:
  secret_key_base: 91b6e9d0d443957ba61eddd3e20340976090ad9581242db1988c6032eb7c986b153dd57c5216a43b246dbb4033af45027eae39820fdbac35088111e7d36012c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
